on:
  - pull_request
  - push

name: CI-Windows

jobs:
  run:
    name: Tests
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: sockets, json, curl

    - name: Install dependencies with composer
      run: composer install
